### ISSUE TITLE
Podatkovne tabele za šifrante

### ISSUE THREAD

**Issue by nunar** [nunar/prometna-varnost#1]
Šifrante, opisane v https://github.com/nunar/prometna-varnost/blob/master/README.md bi bilo potrebno spraviti v podatkovne tabele. Ime tabele = ime šifranta, stolpca sta lahko **key** in **description**, pri čemer za **key** izberemo ustrezno dolžino (1 ali 2).

**Comment by andrazjelenc** [comment]
Amm kje naj naredim podatkovne tabele ?

**Comment by nunar** [comment]
Lokalno. V MySQL?

**Comment by andrazjelenc** [comment]
Aha dojamem ja. Bom naredil

**Comment by andrazjelenc** [comment]
Done

**Comment by nunar** [comment]
Manjka še šifrant za občine. Glej data/XXXX/sifrant.txt.

**Comment by andrazjelenc** [comment]
zdej pa bo
